export const data = {
    "jokes": [
      "Why did the developer go broke? Because he used up all his cache!",
      "Why don't programmers like nature? It has too many bugs!",
      "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
      "Why was the JavaScript developer sad? Because he didn't 'null' his feelings!",
      "Why do programmers prefer iOS development over Android development? Because on iOS, you don't have to deal with Java!",
      "Why did the programmer quit his job? Because he didn't get arrays!",
      "Why did the developer break up with his keyboard? It had too many issues!",
      "Why do programmers hate nature? It has too many bugs!",
      "What did the database say to the query? 'You complete me.'",
      "Why did the programmer go broke buying the latest tech gadgets? Because he couldn't find the right framework!",
      "How do you comfort a JavaScript bug? You console it!",
      "Why don't programmers like to go outside? The sun causes too many reflections.",
      "Why do programmers always mix up Christmas and Halloween? Because Oct(31) == Dec(25).",
      "Why do programmers prefer iOS development over Android development? Because it's less Java!",
      "Why did the programmer sit at the corner of the room? Because he wanted to be in the 'array'!",
      "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
      "Why did the JavaScript developer break up with Java? Because it had too many 'NullPointerExceptions.'",
      "How do you comfort a JavaScript bug? You console it!",
      "Why don't programmers like to go outside? The sun causes too many 'exceptions.'",
      "Why don't programmers like to go outside? The sunlight causes too many 'bugs.'",
      "Why don't programmers like to go outside? The open air has too many 'frameworks.'",
      "Why did the programmer leave his job? He didn't get arrays!",
      "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
      "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
      "Why did the programmer go broke buying gadgets? Because he couldn't find the 'right click!'",
      "Why don't programmers like to go outside? Because the 'outside world' has no API.",
      "Why don't programmers like to go outside? Because the 'outside' has too many 'versions.'",
      "Why did the JavaScript developer go broke? Because he didn't 'get' JavaScript!",
      "Why don't programmers like nature? It has too many 'bugs.'",
      "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!"
    ],
    "emojis": [
      "🤣",
      "😂",
      "😆",
      "😅",
      "🙃",
      "🤪",
      "😎",
      "🤓",
      "😜",
      "👾",
      "🤖",
      "👻",
      "💻",
      "🖥️",
      "📱",
      "⌨️",
      "🌟",
      "💡",
      "🚀",
      "🔥",
      "💬",
      "✨",
      "🎉",
      "💯",
      "🙌",
      "👍",
      "👏",
      "🔗"
    ]
  };  