export const data = {
  "jokes": [
    "Code executed successfully. 🚀",
    "No errors found. ✅",
    "Debugging complete. 🧐",
    "All tests passed. 🎉",
    "Programmers' paradise. 😇",
    "No bugs in sight. 🐞",
    "Code is flawless. 💎",
    "No crashes today. 🌟",
    "100% code coverage. 💯",
    "Effortless debugging. 🧰",
    "Error-free coding. 🙌",
    "Coding made easy. 🤓",
    "Bugs be gone! 🦟",
    "Clean code, no issues. 🧹",
    "Debugging wizardry. 🪄",
    "Code sailing smoothly. ⛵",
    "Flawless execution. 💼",
    "Bug-free zone. 🚫",
    "Code perfection. 🏆",
    "Efficient debugging. 🔍",
    "No more bug hunts. 🔍",
    "Coding nirvana. 🌈",
    "Troubleshoot like a pro. 🕵️",
    "Programming bliss. 😌",
    "No coding drama today. 🎭",
    "Coding at its finest. 🎨",
    "Error? What error? 🤷‍♂️",
    "Coding serenity. 🧘‍♂️",
    "Bug-free masterpiece. 🖼️",
    "Smooth code flow. 🌊",
    "Flawless code orchestra. 🎼",
    "Debugging with ease. 🎛️",
    "No bugs, just features! 🛠️",
    "Code running like a dream. 💭",
    "Flawless coding victory! 🏅",
    "Coding excellence achieved. 🏆",
    "Zero bug policy today. 🚫🐛",
    "Debugging champ mode. 🥇",
    "Code harmony achieved. 🎶",
    "Programming serendipity. 🍀",
    "No code turbulence here. ✈️",
    "Coding is pure magic. 🎩✨",
    "Code blissfully bug-free. 🙏",
    "Zero bug hero. 🦸‍♂️",
    "Bug exterminator at work. 🐜",
    "Code cruising smoothly. 🚤",
    "No code errors detected. 📊",
    "Debugging mastery unlocked. 🔓",
    "Coding zen achieved. ☯️",
    "Code success party time! 🎈",
    "Zero bugs, endless smiles. 😄"
  ],
  "emojis": [
    "🤣",
    "😂",
    "😆",
    "😅",
    "🙃",
    "🤪",
    "😎",
    "🤓",
    "😜",
    "👾",
    "🤖",
    "👻",
    "💻",
    "🖥️",
    "📱",
    "⌨️",
    "🌟",
    "💡",
    "🚀",
    "🔥",
    "💬",
    "✨",
    "🎉",
    "💯",
    "🙌",
    "👍",
    "👏",
    "🔗",
    "🤩",
    "🤯",
    "🧐",
    "🧙‍♂️",
    "🎃",
    "🌈",
    "🍕",
    "🍺",
    "🎸",
    "🎮",
    "🎵",
    "🏆",
    "🏝️",
    "🌺",
    "🚲",
    "🏕️",
    "🎶",
    "🎨",
    "🌄",
    "🍔",
    "🌮",
    "🍦",
    "🍰",
    "🍹",
    "🍾",
    "🎈",
    "🎁",
    "🎂",
    "🎊",
    "🎋",
    "🎍",
    "🎎",
    "🎏",
    "🎐",
    "🎥",
    "🎤",
    "🎧",
    "🎺",
    "🎻",
    "🎼",
    "🥁",
    "🎲",
    "🎳",
    "🎮",
    "🎯",
    "🎱",
    "🎰",
    "🎳",
    "🚀",
    "🛸",
    "🚁",
    "🛶",
    "🚤",
    "🚢",
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚈",
    "🚉",
    "🚊",
    "🚝",
    "🚞",
    "🚟",
    "🚠",
    "🚡",
    "🚢",
    "🚣",
    "🚤",
    "🛶",
    "🛳️",
    "🛴",
    "🛵",
    "🚲",
    "🛹",
    "🚏",
    "🛣️",
    "🛤️",
    "🛢️",
    "🛠️",
    "🛡️",
    "🛤️",
    "🛢️",
    "🛠️",
    "🛡️",
    "🛰️",
    "🚀",
    "🛸",
    "🛬",
    "🛫",
    "🛩️"
  ]
};  